name: deepchem-server-env
dependencies:
  - python=3.11
  - conda-forge::pdbfixer
  - conda-forge::vina
  - nvidia::cudatoolkit
  - conda-forge::openfe=1.1.0
  - conda-forge::openmm=8.0
  - pip
  - pip:
      - pandas
      - python-multipart
      - fastapi
      - pytest
      - uvicorn[standard]
      - numpy>=1.24.0,<2.0
      - scikit-learn>=1.3.2,<1.6
      - pillow==10.3.0
      - rdkit==2022.9.5
      - torchdata<0.8.0
      - --pre
      - deepchem
      - torch==2.1.0
      - transformers==4.39.3
      - dgl
      - dgllife
      - torch_geometric
      - importlib_resources