name: Run PyDS test on live server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test-pyds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clean up unnecessary pre-installed software
        uses: ./.github/actions/cleanup

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Make docker script executable
        run: chmod +x ./docker.sh

      - name: Run build and run script
        run: ./docker.sh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install --no-cache-dir -r pyds/requirements.txt &&
          pip install --no-cache-dir -r pyds/tests/requirements.txt

      - name: Make pytest script executable
        run: chmod +x ./scripts/pytest_pyds.sh

      - name: Run tests
        run: |
          if ./scripts/pytest_pyds.sh; then
            echo "Tests passed"
            exit 0
          else
            ./docker.sh -l
            echo "Tests failed! Check the logs above for debugging."
            exit 1
          fi
